DROP TABLE ORDER#;
DROP TABLE ORDERDETAILS;
DROP TABLE PLAYERSTATS;
DROP TABLE SEATS;
DROP TABLE STADIUM;
DROP TABLE DEPARTMENT;
DROP TABLE GAMES;
DROP TABLE EMPLOYEE;
DROP TABLE PLAYERS;
DROP TABLE CLUB;

CREATE TABLE CLUB(
CLUB# INT NOT NULL,
CLUB_NAME VARCHAR(20),
CLUB_STADIUMNAME VARCHAR(20),
CITY VARCHAR(20),
CLUB_MANAGER_LNAME VARCHAR(10),
CLUB_MANAGER_FNAME VARCHAR(10),
CONSTRAINT CLUB_CLUB#_PK PRIMARY KEY (CLUB#));	

CREATE TABLE PLAYERS(
PLAYER# INT NOT NULL,
CLUB# INT,
FIRST_NAME VARCHAR(20),
LAST_NAME VARCHAR(20),
COUNTRY VARCHAR(20),
AGE INT,
PLAYER_POSITION VARCHAR(10),
CONSTRAINT PLAYERS_PLAYER#_PK PRIMARY KEY (PLAYER#),
CONSTRAINT PLAYERS_CLUB_ID_FK FOREIGN KEY (CLUB#) REFERENCES CLUB(CLUB#))

CREATE TABLE DEPARTMENT(
DEPARTMENT# INT,
DEPARTMENT_NAME VARCHAR(10),
CONSTRAINT DEPARTMENT_DEPARTMENT#_PK PRIMARY KEY (DEPARTMENT#))

CREATE TABLE EMPLOYEE(
EMPLOYEE# INT,
EMPLOYEE_FNAME VARCHAR(20),
EMPLOYEE_LNAME VARCHAR(20),
EMPLOYEE_POSITION VARCHAR(10),
EMPLOYEE_SALARY INT,
--DEPARTMENT# INT,
CONSTRAINT EMPLOYEE_EMPLOYEE#_PK PRIMARY KEY (EMPLOYEE#)
--,CONSTRAINT EMPLOYEE_DEPARTMENT#_FK FOREIGN KEY (DEPARTMENT#) REFERENCES DEPARTMENT(DEPARTMENT#)
)

select * from employee
alter table employee 
add stateadd varchar(30) 
select * from employee
INSERT INTO employee ( stateadd ) VALUES
('Mankato'),
('mankato'),
('le suer');


CREATE TABLE GAMES(
GAME# INT,
CLUB# INT,
HOME VARCHAR(20),
AWAY VARCHAR(20),
GAME_RESULT VARCHAR(5),
GAME_DATE DATE,
CONSTRAINT GAMES_GAME#_PK PRIMARY KEY (GAME#),
CONSTRAINT GAMES_CLUB#_FK FOREIGN KEY (CLUB#) REFERENCES CLUB(CLUB#))

select * from games
ALter table games
add attendance varchar(20)
alter table games
alter column win float
alter table games
alter column draw float
alter table games
alter column lose float
CREATE TABLE STADIUM(
CLUB# INT,
STADIUM# INT,
STADIUM_NAME VARCHAR(20),
CITY VARCHAR(20),
CAPACITY INT,
CONSTRAINT STADIUM_STADIUM#_PK PRIMARY KEY (STADIUM#),
CONSTRAINT STADIUM_CLUB#_FK FOREIGN KEY (CLUB#) REFERENCES CLUB(CLUB#))

CREATE TABLE SEATS(
SEAT# INT,
SECTION# VARCHAR(3),
ZONE# INT,
STADIUM# INT,
CONSTRAINT SEATS_SEAT#_SECTION#_ZONE#_PK PRIMARY KEY(SEAT#, SECTION#, ZONE#),
CONSTRAINT SEATS_STADIUM#_FK FOREIGN KEY (STADIUM#) REFERENCES STADIUM(STADIUM#))

CREATE TABLE PLAYERSTATS(
PLAYER# INT,
FIRST_NAME VARCHAR(20),
LAST_NAME VARCHAR(20),
PLAYED INT,
GOALS INT,
ASSISTS INT,
YELLOWCARD INT,
REDCARD INT,
CONSTRAINT PLAYERSTATS_PLAYER#_PK PRIMARY KEY(PLAYER#),
CONSTRAINT PLAYERSTATS_PLAYER#_FK FOREIGN KEY (PLAYER#) REFERENCES PLAYERS(PLAYER#))

CREATE TABLE ORDERDETAILS(
TICKET# INT,
STADIUM# INT,
FIRST_NAME VARCHAR(20),
LAST_NAME VARCHAR(20),
STREETADDRESS VARCHAR(20),
CITY VARCHAR(20),
STATEADD VARCHAR(20),
NUMBEROFTICKETS INT,
CREDITCARD INT,
CCV INT,
EXPIRE DATE,
PRICE INT,
CONSTRAINT ORDERDETAILS_TICKET#_PK PRIMARY KEY(TICKET#),
CONSTRAINT ORDERDETAILS_STADIUM#_FK FOREIGN KEY (STADIUM#) REFERENCES STADIUM(STADIUM#))
select * from ORDERDETAILS


alter table orderdetails
add constraint orderdetails_game#_fk foreign key (game#) references games(game#)
CREATE TABLE ORDER#(
STADIUM# INT,
TICKET# INT,
HOMETEAM VARCHAR(20),
AWAYTEAM VARCHAR(20),
PRICE INT,
SEAT# INT,
SECTION# VARCHAR(3),
ZONE# INT,
CONSTRAINT ORDER_STADIUM#_TICKET#_FK PRIMARY KEY (STADIUM#, TICKET#),
CONSTRAINT ORDER#_SEAT#_SECTION#_ZONE#_PK FOREIGN KEY(SEAT#, SECTION#, ZONE#) REFERENCES SEATS(SEAT#, SECTION#, ZONE#),
CONSTRAINT ORDER#_TICKET#_PRICE_FK FOREIGN KEY (TICKET#) REFERENCES ORDERDETAILS (TICKET#))

--ALTER TABLE EMPLOYEE ALTER COLUMN EMPLOYEE_POSITION VARCHAR(50)

USE Arsenal;

SELECT * FROM information_schema.tables;